language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.pip
  - pip install nose coverage coveralls
after_success:
  - coveralls
script: nosetests --cover-erase --with-coverage --cover-package=dict_tools
